# builds the obslytics binary image
# does not allow for python scripting for pre-processing of data

FROM golang:1.18

WORKDIR /usr/src/app

RUN mkdir -p /go/pkg/mod/github.com
RUN mkdir /usr/src/io

COPY ./pkg /go/pkg/mod/github.com/
COPY run.sh ./
RUN chmod +x run.sh
ADD obslytics ./
RUN make build

CMD ["./run.sh"]

